"""add mode and draft_report to chat

Revision ID: 23214191b29d
Revises: 56e36ed6945f
Create Date: 2026-02-12 10:14:34.799506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23214191b29d'
down_revision = '56e36ed6945f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('draft_report', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_column('draft_report')
        batch_op.drop_column('mode')

    # ### end Alembic commands ###
