"""add mode and draft_report to chat

Revision ID: b9187cf56695
Revises: 56e36ed6945f
Create Date: 2026-02-12 11:02:25.066297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9187cf56695'
down_revision = '56e36ed6945f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(length=30), server_default='maintenance', nullable=False))
        batch_op.add_column(sa.Column('draft_report', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_column('draft_report')
        batch_op.drop_column('mode')

    # ### end Alembic commands ###
