"""Add image and manual

Revision ID: fb38535a53dc
Revises: 56e36ed6945f
Create Date: 2026-02-12 11:13:10.601441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb38535a53dc'
down_revision = '56e36ed6945f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('manual', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_column('manual')
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###
